output "api_gateway_url" {
  description = "URL for invoking API Gateway."
  value       = aws_api_gateway_stage.gateway.invoke_url
}

resource "local_file" "browser_config" {
  content  = <<-EOT
    // This file is dynamically generated by Terraform.
    export const apiUrl = "${aws_api_gateway_stage.gateway.invoke_url}";
  EOT
  filename = "${local.browser_dir}/terraform-output.js"
}
