# terraform {
#   required_providers {
#     aws = {
#       source  = "hashicorp/aws"
#       version = "5.56.1"
#     }
#   }
#   backend "s3" {
#     bucket = "nicks-terraform-states"
#     region = "ap-southeast-2"
#   }
# }

# provider "aws" {
#   region = "ap-southeast-2"
#   default_tags {
#     tags = local.tags
#   }
# }

# module "shared_locals" {
#   source = "../../modules/shared_locals"
# }

# locals {
#   region           = module.shared_locals.region
#   environment      = module.shared_locals.environment
#   prefix_lower     = module.shared_locals.prefix_lower
#   prefix_parameter = module.shared_locals.prefix_parameter
#   tags             = module.shared_locals.tags
# }

# resource "aws_route53_delegation_set" "name_servers" {
#   // Group of 4 name servers, generated by AWS. These four values must be 
#   // the same for both the hosted zone and the registered domain.
#   reference_name = "WebsiteDNS"
# }
