[package]
name = "endpoints"
version = "0.1.0"
edition = "2021"

[dependencies]
database.workspace = true
houses.workspace = true
anyhow = "1.0"
axum ="0.8.1"
axum-aws-lambda = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
utoipa = "5.3"
utoipa-axum = "0.2"
