/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapRequest
 */
export interface MapRequest {
    /**
     * 
     * @type {string}
     * @memberof MapRequest
     */
    cityCode: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MapRequest
     */
    requirementIds: Array<string>;
}

/**
 * Check if a given object implements the MapRequest interface.
 */
export function instanceOfMapRequest(value: object): value is MapRequest {
    if (!('cityCode' in value) || value['cityCode'] === undefined) return false;
    if (!('requirementIds' in value) || value['requirementIds'] === undefined) return false;
    return true;
}

export function MapRequestFromJSON(json: any): MapRequest {
    return MapRequestFromJSONTyped(json, false);
}

export function MapRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cityCode': json['city_code'],
        'requirementIds': json['requirement_ids'],
    };
}

export function MapRequestToJSON(json: any): MapRequest {
    return MapRequestToJSONTyped(json, false);
}

export function MapRequestToJSONTyped(value?: MapRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city_code': value['cityCode'],
        'requirement_ids': value['requirementIds'],
    };
}

