/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapTileResponse
 */
export interface MapTileResponse {
    /**
     * 
     * @type {string}
     * @memberof MapTileResponse
     */
    h3Index: string;
}

/**
 * Check if a given object implements the MapTileResponse interface.
 */
export function instanceOfMapTileResponse(value: object): value is MapTileResponse {
    if (!('h3Index' in value) || value['h3Index'] === undefined) return false;
    return true;
}

export function MapTileResponseFromJSON(json: any): MapTileResponse {
    return MapTileResponseFromJSONTyped(json, false);
}

export function MapTileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapTileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'h3Index': json['h3_index'],
    };
}

export function MapTileResponseToJSON(json: any): MapTileResponse {
    return MapTileResponseToJSONTyped(json, false);
}

export function MapTileResponseToJSONTyped(value?: MapTileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'h3_index': value['h3Index'],
    };
}

