/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseHouseResponseItemsInner } from './PaginatedResponseHouseResponseItemsInner';
import {
    PaginatedResponseHouseResponseItemsInnerFromJSON,
    PaginatedResponseHouseResponseItemsInnerFromJSONTyped,
    PaginatedResponseHouseResponseItemsInnerToJSON,
    PaginatedResponseHouseResponseItemsInnerToJSONTyped,
} from './PaginatedResponseHouseResponseItemsInner';

/**
 * 
 * @export
 * @interface PaginatedResponseHouseResponse
 */
export interface PaginatedResponseHouseResponse {
    /**
     * 
     * @type {Array<PaginatedResponseHouseResponseItemsInner>}
     * @memberof PaginatedResponseHouseResponse
     */
    items: Array<PaginatedResponseHouseResponseItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseHouseResponse
     */
    lastEvaluatedKey?: string | null;
}

/**
 * Check if a given object implements the PaginatedResponseHouseResponse interface.
 */
export function instanceOfPaginatedResponseHouseResponse(value: object): value is PaginatedResponseHouseResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PaginatedResponseHouseResponseFromJSON(json: any): PaginatedResponseHouseResponse {
    return PaginatedResponseHouseResponseFromJSONTyped(json, false);
}

export function PaginatedResponseHouseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseHouseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PaginatedResponseHouseResponseItemsInnerFromJSON)),
        'lastEvaluatedKey': json['last_evaluated_key'] == null ? undefined : json['last_evaluated_key'],
    };
}

export function PaginatedResponseHouseResponseToJSON(json: any): PaginatedResponseHouseResponse {
    return PaginatedResponseHouseResponseToJSONTyped(json, false);
}

export function PaginatedResponseHouseResponseToJSONTyped(value?: PaginatedResponseHouseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PaginatedResponseHouseResponseItemsInnerToJSON)),
        'last_evaluated_key': value['lastEvaluatedKey'],
    };
}

