/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseHouseResponseItemsInner } from './PaginatedResponseHouseResponseItemsInner';
import {
    PaginatedResponseHouseResponseItemsInnerFromJSON,
    PaginatedResponseHouseResponseItemsInnerFromJSONTyped,
    PaginatedResponseHouseResponseItemsInnerToJSON,
    PaginatedResponseHouseResponseItemsInnerToJSONTyped,
} from './PaginatedResponseHouseResponseItemsInner';

/**
 * 
 * @export
 * @interface PaginatedResponseHouseResponse
 */
export interface PaginatedResponseHouseResponse {
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponse
     */
    currentPage: number;
    /**
     * 
     * @type {Array<PaginatedResponseHouseResponseItemsInner>}
     * @memberof PaginatedResponseHouseResponse
     */
    items: Array<PaginatedResponseHouseResponseItemsInner>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponse
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponse
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PaginatedResponseHouseResponse interface.
 */
export function instanceOfPaginatedResponseHouseResponse(value: object): value is PaginatedResponseHouseResponse {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PaginatedResponseHouseResponseFromJSON(json: any): PaginatedResponseHouseResponse {
    return PaginatedResponseHouseResponseFromJSONTyped(json, false);
}

export function PaginatedResponseHouseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseHouseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'],
        'items': ((json['items'] as Array<any>).map(PaginatedResponseHouseResponseItemsInnerFromJSON)),
        'pageSize': json['page_size'],
        'totalItems': json['total_items'],
        'totalPages': json['total_pages'],
    };
}

export function PaginatedResponseHouseResponseToJSON(json: any): PaginatedResponseHouseResponse {
    return PaginatedResponseHouseResponseToJSONTyped(json, false);
}

export function PaginatedResponseHouseResponseToJSONTyped(value?: PaginatedResponseHouseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'items': ((value['items'] as Array<any>).map(PaginatedResponseHouseResponseItemsInnerToJSON)),
        'page_size': value['pageSize'],
        'total_items': value['totalItems'],
        'total_pages': value['totalPages'],
    };
}

