/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedResponseHouseResponseItemsInner
 */
export interface PaginatedResponseHouseResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    h3Index: string;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    lon: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    numBathrooms: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    numBedrooms: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    numCarspaces: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    priceLower: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    priceUpper: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    propertyType: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseHouseResponseItemsInner
     */
    url: string;
}

/**
 * Check if a given object implements the PaginatedResponseHouseResponseItemsInner interface.
 */
export function instanceOfPaginatedResponseHouseResponseItemsInner(value: object): value is PaginatedResponseHouseResponseItemsInner {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('h3Index' in value) || value['h3Index'] === undefined) return false;
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lon' in value) || value['lon'] === undefined) return false;
    if (!('numBathrooms' in value) || value['numBathrooms'] === undefined) return false;
    if (!('numBedrooms' in value) || value['numBedrooms'] === undefined) return false;
    if (!('numCarspaces' in value) || value['numCarspaces'] === undefined) return false;
    if (!('priceLower' in value) || value['priceLower'] === undefined) return false;
    if (!('priceUpper' in value) || value['priceUpper'] === undefined) return false;
    if (!('propertyType' in value) || value['propertyType'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PaginatedResponseHouseResponseItemsInnerFromJSON(json: any): PaginatedResponseHouseResponseItemsInner {
    return PaginatedResponseHouseResponseItemsInnerFromJSONTyped(json, false);
}

export function PaginatedResponseHouseResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseHouseResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'h3Index': json['h3_index'],
        'lat': json['lat'],
        'lon': json['lon'],
        'numBathrooms': json['num_bathrooms'],
        'numBedrooms': json['num_bedrooms'],
        'numCarspaces': json['num_carspaces'],
        'priceLower': json['price_lower'],
        'priceUpper': json['price_upper'],
        'propertyType': json['property_type'],
        'url': json['url'],
    };
}

export function PaginatedResponseHouseResponseItemsInnerToJSON(json: any): PaginatedResponseHouseResponseItemsInner {
    return PaginatedResponseHouseResponseItemsInnerToJSONTyped(json, false);
}

export function PaginatedResponseHouseResponseItemsInnerToJSONTyped(value?: PaginatedResponseHouseResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'h3_index': value['h3Index'],
        'lat': value['lat'],
        'lon': value['lon'],
        'num_bathrooms': value['numBathrooms'],
        'num_bedrooms': value['numBedrooms'],
        'num_carspaces': value['numCarspaces'],
        'price_lower': value['priceLower'],
        'price_upper': value['priceUpper'],
        'property_type': value['propertyType'],
        'url': value['url'],
    };
}

