/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequirementScoreResponse
 */
export interface RequirementScoreResponse {
    /**
     * 
     * @type {string}
     * @memberof RequirementScoreResponse
     */
    requirementId: string;
    /**
     * 
     * @type {number}
     * @memberof RequirementScoreResponse
     */
    score: number;
}

/**
 * Check if a given object implements the RequirementScoreResponse interface.
 */
export function instanceOfRequirementScoreResponse(value: object): value is RequirementScoreResponse {
    if (!('requirementId' in value) || value['requirementId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function RequirementScoreResponseFromJSON(json: any): RequirementScoreResponse {
    return RequirementScoreResponseFromJSONTyped(json, false);
}

export function RequirementScoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequirementScoreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requirementId': json['requirement_id'],
        'score': json['score'],
    };
}

export function RequirementScoreResponseToJSON(json: any): RequirementScoreResponse {
    return RequirementScoreResponseToJSONTyped(json, false);
}

export function RequirementScoreResponseToJSONTyped(value?: RequirementScoreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requirement_id': value['requirementId'],
        'score': value['score'],
    };
}

