/* tslint:disable */
/* eslint-disable */
/**
 * endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PaginatedResponseHouseResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PaginatedResponseHouseResponseFromJSON,
    PaginatedResponseHouseResponseToJSON,
} from '../models/index';

export interface GetHousesRequest {
    limit?: number;
    lastEvaluatedKey?: string;
}

/**
 * 
 */
export class HouseApi extends runtime.BaseAPI {

    /**
     */
    async getHousesRaw(requestParameters: GetHousesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseHouseResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['lastEvaluatedKey'] != null) {
            queryParameters['last_evaluated_key'] = requestParameters['lastEvaluatedKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/houses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseHouseResponseFromJSON(jsonValue));
    }

    /**
     */
    async getHouses(requestParameters: GetHousesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseHouseResponse> {
        const response = await this.getHousesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
